# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Build
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      docker pull osrf/ros:melodic-desktop-full
      docker run -v `pwd`:/mnt osrf/ros:melodic-desktop-full bash -c "cd /mnt;./exec_offline-2d.sh"
      ls -lah .
      GIT_TAG=`git tag -l --points-at HEAD|head -n 1`
      if [ -z "$GIT_TAG" ]; then exit 0; fi
      mkdir -p artifacts
      mv -f out*.ogv artifacts/
      docker run -v `pwd`:/mnt golang:1.11.2 bash -x -c "cd /mnt; go get github.com/tcnksm/ghr ; ghr -t ${GITHUB_TOKEN} -u $(echo $BUILD_REPOSITORY_NAME | cut -f1 -d/) -r $(echo $BUILD_REPOSITORY_NAME | cut -f2 -d/) -c ${BUILD_SOURCEVERSION} -delete ${GIT_TAG} ./artifacts/"
    displayName: 'Run a multi-line script'

